### ISSUE TITLE
Not working with zshell

### ISSUE THREAD

**Issue by aarobc** [schischi/xcwd#12]
If I'm using zshell with gnome-terminal, it only returns my home directory. I placed the following in my ~/.i3/config:

    bindsym $mod+g exec gnome-terminal --working-directory=`xcwd`

However it will only work if I'm running bash in gnome-terminal. 
If it helps, my dotfiles are located here: 
http://github.com/aarobc/dotfiles

**Comment by cinemast** [comment]
This is a bug of the gnome-terminal with zsh: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=755546
